/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VPT */

#ifndef _Included_VPT
#define _Included_VPT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     VPT
 * Method:    main1
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_VPT_cppMain
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     VPT
 * Method:    forceLogout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_VPT_forceLogout
  (JNIEnv *, jclass);

/*
 * Class:     VPT
 * Method:    socketClosed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_VPT_socketClosed
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
