/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class common_networking_NetworkingJNI */

#ifndef _Included_common_networking_NetworkingJNI
#define _Included_common_networking_NetworkingJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     common_networking_NetworkingJNI
 * Method:    createClient
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_common_networking_NetworkingJNI_createClient
  (JNIEnv *, jclass);

/*
 * Class:     common_networking_NetworkingJNI
 * Method:    dispose
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_common_networking_NetworkingJNI_dispose
  (JNIEnv *, jclass, jstring);

/*
 * Class:     common_networking_NetworkingJNI
 * Method:    sendData
 * Signature: (Ljava/lang/String;[BI)V
 */
JNIEXPORT void JNICALL Java_common_networking_NetworkingJNI_sendData
  (JNIEnv *, jclass, jstring, jbyteArray, jint);

/*
 * Class:     common_networking_NetworkingJNI
 * Method:    recieveData
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_common_networking_NetworkingJNI_recieveData
  (JNIEnv *, jclass, jstring);

/*
 * Class:     common_networking_NetworkingJNI
 * Method:    createServer
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_common_networking_NetworkingJNI_createServer
  (JNIEnv *, jclass);

/*
 * Class:     common_networking_NetworkingJNI
 * Method:    accept
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_common_networking_NetworkingJNI_accept
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
